# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "bt60"
product_name = "bt60"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "polarity works"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P1_11", "P1_10", "P1_13", "P1_15", "P0_03", "P0_02", "P0_28", "P0_29", "P0_30", "P0_31", "P0_05", "P0_07", "P1_09", "P0_12", "P0_23"]

output_pins = ["P0_22", "P1_00", "P1_03", "P1_01", "P1_02", "P1_04"]

# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 15
cols = 5
layers = 1
keymap = [
    [
        ["ESC", "KC1", "KC2", "KC3", "KC4", "KC5", "KC6", "KC7", "KC8", "KC9", "KC0", "Minus", "Equal", "Backspace", "Delete"],
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "LeftBracket", "RightBracket", "Backslash"],
        ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote", "Return"],
        ["LShift", "__", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "RightShift", "ArrowUp", "__"],
        ["LCTRL", "LGUI", "LAlt", "Space", "RAlt", "RCTRL", "LEFT", "Down", "Right"]
    ],

]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false

[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"
# Or
# battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806
charge_state.pin = "P0_25"
charge_state.low_active = false
charge_led.pin = "P0_29"
charge_led.low_active = false
